# Generated by Django 4.0.4 on 2022-08-04 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('excelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfileuser',
            name='excel_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='excelapp.excelfile'),
        ),
        migrations.AlterField(
            model_name='excelfileuser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
