# Generated by Django 4.0.4 on 2022-08-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('excelapp', '0002_delete_exceluser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='excel')),
            ],
            options={
                'verbose_name': 'excel file',
                'verbose_name_plural': 'excel files',
            },
        ),
    ]
