# Generated by Django 4.0.4 on 2022-08-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelapp', '0002_alter_excelfileuser_excel_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfile',
            name='comments',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
