# Generated by Django 4.0.4 on 2022-08-11 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('excelapp', '0003_alter_excelfile_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSheetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user sheet data',
                'verbose_name_plural': 'users sheet data',
            },
        ),
    ]
