# Generated by Django 4.0.4 on 2022-08-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelapp', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfile',
            name='file',
            field=models.FileField(upload_to='excelapp/static/excelapp/excel'),
        ),
    ]
