# Generated by Django 4.0.4 on 2022-08-03 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import excelapp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('excelapp', '0004_alter_excelfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfile',
            name='file',
            field=models.FileField(upload_to='excelapp/static/excelapp/excel', validators=[excelapp.models.validate_file_extension]),
        ),
        migrations.CreateModel(
            name='ExcelFileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='excelapp.excelfile')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
